services:
  postgres:
    container_name: postgres_container
    image: postgres:17-bookworm
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data
      - TZ=Asia/Seoul
    shm_size: 2GB
    deploy:
      resources:
        limits:
          memory: 8G
    command: |
        postgres
          -c log_timezone=Asia/Seoul
          -c TimeZone=Asia/Seoul
          -c shared_preload_libraries=pg_stat_statements
          -c pg_stat_statements.track=all
          -c max_connections=200
          -c shared_buffers=2GB
          -c effective_cache_size=6GB
          -c maintenance_work_mem=512MB
          -c checkpoint_completion_target=0.9
          -c wal_buffers=32MB
          -c default_statistics_target=100
          -c random_page_cost=1.1
          -c effective_io_concurrency=300
          -c work_mem=16MB
          -c huge_pages=off
          -c min_wal_size=128MB
          -c max_wal_size=4GB
